DROP TABLE IF EXISTS superhero;
DROP TABLE IF EXISTS assistant;
DROP TABLE IF EXISTS power;

CREATE TABLE superhero (
  id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  name VARCHAR(20) NOT NULL,
  alias VARCHAR(40),
  origin VARCHAR(40),
  CONSTRAINT pk_superhero PRIMARY KEY  (id)
);

CREATE TABLE assistant (
  id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  name VARCHAR(20) NOT NULL,
  CONSTRAINT pk_assistant PRIMARY KEY  (id)
);

CREATE TABLE power (
  id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  name VARCHAR(20) NOT NULL,
  description VARCHAR(40) NOT NULL,
  CONSTRAINT pk_power PRIMARY KEY  (id)
);